// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7EbQAtQHuH4Xo9AVZukhqnct3d23JmQ',
    appId: '1:1076501063547:web:459c87204722a1a79c3fde',
    messagingSenderId: '1076501063547',
    projectId: 'tic-tac-toe-a423a',
    authDomain: 'tic-tac-toe-a423a.firebaseapp.com',
    storageBucket: 'tic-tac-toe-a423a.appspot.com',
    measurementId: 'G-E5WMVFVY9J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86_AnJVrqByx2mBp0XvVxiLhsHDpCKbs',
    appId: '1:1076501063547:ios:fc473f4761819d7f9c3fde',
    messagingSenderId: '1076501063547',
    projectId: 'tic-tac-toe-a423a',
    storageBucket: 'tic-tac-toe-a423a.appspot.com',
    iosBundleId: 'com.chantsocial.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD86_AnJVrqByx2mBp0XvVxiLhsHDpCKbs',
    appId: '1:1076501063547:ios:40cfcc2011ba135c9c3fde',
    messagingSenderId: '1076501063547',
    projectId: 'tic-tac-toe-a423a',
    storageBucket: 'tic-tac-toe-a423a.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7EbQAtQHuH4Xo9AVZukhqnct3d23JmQ',
    appId: '1:1076501063547:web:80062a9341ee83909c3fde',
    messagingSenderId: '1076501063547',
    projectId: 'tic-tac-toe-a423a',
    authDomain: 'tic-tac-toe-a423a.firebaseapp.com',
    storageBucket: 'tic-tac-toe-a423a.appspot.com',
    measurementId: 'G-BM7WT3E43R',
  );
}
